# (Service này thường không cần Database riêng, nếu có dùng thì thêm vào đây giống các service trên)

# --- RABBITMQ (Quan trọng với Notification) ---
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_USERNAME:admin}
spring.rabbitmq.password=${RABBIT_PASSWORD:admin}

# --- EUREKA ---
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
eureka.instance.prefer-ip-address=true

# --- EMAIL CONFIG ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:longyl1212005@gmail.com}
spring.mail.password=${MAIL_PASSWORD:nkjb wbtw razk dccf}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
